import type { CreateProductPayload } from "@/lib/catalog.types";

export type DemoProductSeed = Omit<CreateProductPayload, "categoryId"> & {
    categorySlug: "dien-thoai" | "laptop" | "thoi-trang";
};

/** Catalog demo ~35 SP ACTIVE — seed qua POST /products (cùng payload form admin). */
export const DEMO_PRODUCTS: DemoProductSeed[] = [
    {
        categorySlug: "thoi-trang",
        name: "Áo sơ mi nam Oxford",
        description:
            "Áo sơ mi Oxford form regular, dễ phối đồ công sở và dạo phố.",
        price: 289000,
        discountPrice: 249000,
        quantity: 80,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Quần jean slim nam",
        description: "Jean slim stretch, co giãn nhẹ, phù hợp mặc hàng ngày.",
        price: 399000,
        discountPrice: 349000,
        quantity: 60,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Váy midi hoa nhí",
        description: "Váy midi chất voan, họa tiết hoa nhí, dáng xoè nhẹ.",
        price: 329000,
        quantity: 45,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Áo khoác denim unisex",
        description: "Khoác jean dày vừa, wash xanh classic.",
        price: 459000,
        discountPrice: 399000,
        quantity: 50,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Hoodie nỉ basic",
        description: "Hoodie nỉ bông, mũ rộng, form oversized.",
        price: 279000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "S", sku: "HD-BASIC-S", price: 279000, quantity: 20, warehouse: "Kho HN" },
            { name: "M", sku: "HD-BASIC-M", price: 279000, quantity: 35, warehouse: "Kho HN" },
            { name: "L", sku: "HD-BASIC-L", price: 289000, quantity: 25, warehouse: "Kho HN" },
            { name: "XL", sku: "HD-BASIC-XL", price: 299000, quantity: 10, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "thoi-trang",
        name: "Quần short kaki",
        description: "Short kaki 5 túi, mặc mát mùa hè.",
        price: 219000,
        quantity: 70,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Áo polo pique nam",
        description: "Polo pique cotton, cổ dệt, form vừa.",
        price: 199000,
        discountPrice: 169000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "Trắng", sku: "POLO-PQ-W", price: 199000, quantity: 40, warehouse: "Kho HN" },
            { name: "Navy", sku: "POLO-PQ-N", price: 199000, quantity: 35, warehouse: "Kho HN" },
            { name: "Đen", sku: "POLO-PQ-B", price: 199000, quantity: 25, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "thoi-trang",
        name: "Chân váy tennis",
        description: "Chân váy tennis xếp ly, có quần trong.",
        price: 189000,
        quantity: 40,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Áo len cổ lọ",
        description: "Áo len gân cổ lọ, giữ ấm nhẹ.",
        price: 259000,
        quantity: 55,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Quần tây công sở",
        description: "Quần tây cạp thường, ly giữa, vải không nhăn.",
        price: 349000,
        quantity: 35,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Áo thun oversized cotton",
        description: "Tee cotton 220gsm, form rộng.",
        price: 159000,
        discountPrice: 139000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "S", sku: "TEE-OV-S", price: 159000, quantity: 30, warehouse: "Kho HN" },
            { name: "M", sku: "TEE-OV-M", price: 159000, quantity: 45, warehouse: "Kho HN" },
            { name: "L", sku: "TEE-OV-L", price: 159000, quantity: 45, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "thoi-trang",
        name: "Giày sneaker canvas",
        description: "Sneaker vải canvas đế cao su, đi nhẹ.",
        price: 429000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "39", sku: "SNK-CV-39", price: 429000, quantity: 12, warehouse: "Kho HN" },
            { name: "40", sku: "SNK-CV-40", price: 429000, quantity: 16, warehouse: "Kho HN" },
            { name: "41", sku: "SNK-CV-41", price: 429000, quantity: 12, warehouse: "Kho HN" },
            { name: "42", sku: "SNK-CV-42", price: 429000, quantity: 8, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "thoi-trang",
        name: "Túi tote canvas",
        description: "Tote vải bố, chứa laptop 14 inch.",
        price: 129000,
        quantity: 80,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Mũ bucket trơn",
        description: "Bucket hat cotton, vành mềm.",
        price: 99000,
        quantity: 60,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "thoi-trang",
        name: "Thắt lưng da PU",
        description: "Thắt lưng khoá kim, bản 3.5cm.",
        price: 149000,
        quantity: 40,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Shoppe Phone A1",
        description: "Smartphone 6.6 inch, pin 5000mAh, camera 50MP.",
        price: 4990000,
        discountPrice: 4590000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "128GB", sku: "SPA1-128", price: 4990000, quantity: 15, warehouse: "Kho HN" },
            { name: "256GB", sku: "SPA1-256", price: 5490000, quantity: 10, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "dien-thoai",
        name: "Shoppe Phone A1 Pro",
        description: "Bản Pro: màn 120Hz, sạc 67W, chống nước IP54.",
        price: 7990000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "256GB Đen", sku: "SPA1P-256-BK", price: 7990000, quantity: 8, warehouse: "Kho HN" },
            { name: "256GB Xanh", sku: "SPA1P-256-BL", price: 7990000, quantity: 6, warehouse: "Kho HN" },
            { name: "512GB Đen", sku: "SPA1P-512-BK", price: 8990000, quantity: 4, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "dien-thoai",
        name: "Shoppe Phone Mini",
        description: "Máy nhỏ gọn 6.1 inch, một tay dễ cầm.",
        price: 3990000,
        discountPrice: 3690000,
        quantity: 30,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Ốp lưng silicone A1",
        description: "Ốp silicon mềm, chống sốc góc.",
        price: 89000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "Trong", sku: "CASE-A1-CL", price: 89000, quantity: 80, warehouse: "Kho HN" },
            { name: "Đen", sku: "CASE-A1-BK", price: 89000, quantity: 70, warehouse: "Kho HN" },
            { name: "Hồng", sku: "CASE-A1-PK", price: 89000, quantity: 50, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "dien-thoai",
        name: "Củ sạc nhanh 20W",
        description: "Adapter USB-C PD 20W, nhỏ gọn.",
        price: 159000,
        discountPrice: 129000,
        quantity: 150,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Tai nghe TWS MiniBuds",
        description: "True wireless, chống ồn ENC, hộp sạc 24h.",
        price: 349000,
        quantity: 70,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Cáp USB-C 1m",
        description: "Cáp nylon bện, sạc/data 60W.",
        price: 59000,
        quantity: 300,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Sạc dự phòng 10000mAh",
        description: "Pin dự phòng 2 cổng, sạc nhanh 22.5W.",
        price: 299000,
        discountPrice: 259000,
        quantity: 80,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Kính cường lực 9H",
        description: "Kính full keo, cứng 9H.",
        price: 49000,
        quantity: 250,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Đế sạc không dây 15W",
        description: "Đế Mag-compatible, đèn báo sạc.",
        price: 219000,
        quantity: 40,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Giá đỡ điện thoại xe hơi",
        description: "Kẹp cửa gió, xoay 360 độ.",
        price: 119000,
        quantity: 55,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "dien-thoai",
        name: "Miếng dán camera",
        description: "Dán bảo vệ cụm camera, bộ 3 miếng.",
        price: 29000,
        quantity: 180,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "ShoppeBook 14",
        description: "Laptop 14 inch IPS, Intel i5, SSD 512GB.",
        price: 14990000,
        discountPrice: 13990000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "16GB RAM", sku: "SB14-16", price: 14990000, quantity: 7, warehouse: "Kho HN" },
            { name: "32GB RAM", sku: "SB14-32", price: 16990000, quantity: 5, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "laptop",
        name: "ShoppeBook 16 Pro",
        description: "Laptop 16 inch 2.5K, GPU rời, bàn phím RGB.",
        price: 24990000,
        quantity: 8,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Balo laptop 15.6 chống sốc",
        description: "Balo ngăn laptop đệm, chống thấm nhẹ.",
        price: 399000,
        discountPrice: 349000,
        quantity: 60,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Chuột không dây silent",
        description: "Chuột 2.4G + Bluetooth, click êm.",
        price: 189000,
        quantity: 90,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Bàn phím cơ mini 68 phím",
        description: "Hot-swap, switch red, layout Việt.",
        price: 890000,
        status: "ACTIVE",
        warehouse: "Kho HN",
        variants: [
            { name: "White", sku: "KB68-WH", price: 890000, quantity: 12, warehouse: "Kho HN" },
            { name: "Black", sku: "KB68-BK", price: 890000, quantity: 13, warehouse: "Kho HN" },
        ],
    },
    {
        categorySlug: "laptop",
        name: "Giá đỡ laptop nhôm",
        description: "Stand nhôm 6 nấc, tản nhiệt tốt.",
        price: 259000,
        quantity: 40,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Hub USB-C 7 trong 1",
        description: "HDMI 4K, USB 3.0, SD/TF, PD 100W.",
        price: 459000,
        discountPrice: 399000,
        quantity: 35,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Túi chống sốc 14 inch",
        description: "Sleeve neoprene, kéo chắc.",
        price: 159000,
        quantity: 70,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
    {
        categorySlug: "laptop",
        name: "Đế tản nhiệt 6 quạt",
        description: "Cooling pad LED, vừa 17 inch.",
        price: 329000,
        quantity: 28,
        status: "ACTIVE",
        warehouse: "Kho HN",
    },
];
